"""Reproduction script for enke_graeber_2023 (text mode).

Auto-generated by run_paper.py. Reruns the exact same simulation.

Requirements:
    pip install edsl

Usage:
    python reproduce.py
"""
import json
from pathlib import Path

from edsl import Survey, AgentList, ScenarioList, Model, ModelList

HERE = Path(__file__).resolve().parent

# --- Load serialized objects ---
with open(HERE / "survey.json") as f:
    survey = Survey.from_dict(json.load(f))

with open(HERE / "agents.json") as f:
    agents = AgentList.from_dict(json.load(f))

models = ModelList([Model(m) for m in ["claude-sonnet-4-6"]])

# Run simulation
job = survey.by(agents).by(models)
results = job.run()
results_df = results.to_pandas()

print(f"Got {len(results_df)} responses")
results_df.to_csv("results_text.csv", index=False)
print(f"Saved to results_text.csv")
