"""Reproduction script for aer_111_10_5 (text mode).

Auto-generated by run_paper.py. Reruns the exact same simulation.

Requirements:
    pip install edsl

Usage:
    python reproduce.py
"""
import json
from pathlib import Path

from edsl import Survey, AgentList, ScenarioList, Model, ModelList

HERE = Path(__file__).resolve().parent

# --- Load serialized objects ---
with open(HERE / "survey.json") as f:
    survey = Survey.from_dict(json.load(f))

with open(HERE / "agents.json") as f:
    agents = AgentList.from_dict(json.load(f))

with open(HERE / "scenarios.json") as f:
    scenarios = ScenarioList.from_dict(json.load(f))

models = ModelList([Model(m) for m in ["claude-sonnet-4-6"]])

# Run per condition with matched sample sizes (as in original study)
condition_ns = {"stim_35": 50, "stim_45": 50, "stim_55": 50, "stim_65": 50, "stim_75": 50, "stim_85": 50, "stim_95": 50}
all_results = []
for scenario in scenarios:
    cond = scenario.get("condition", None)
    cond_n = condition_ns.get(cond, len(agents))
    cond_agents = AgentList(list(agents)[:cond_n])
    print(f"Running condition '{cond}': {len(cond_agents)} agents")
    job = survey.by(cond_agents).by(models).by(ScenarioList([scenario]))
    results = job.run(cache=False, disable_remote_cache=True)
    all_results.append(results.to_pandas())

import pandas as pd
results_df = pd.concat(all_results, ignore_index=True)

print(f"Got {len(results_df)} responses")
results_df.to_csv("results_text.csv", index=False)
print(f"Saved to results_text.csv")
