"""Reproduction script for oprea_2024 (visual mode).

Auto-generated by run_paper.py. Reruns the exact same simulation.

Requirements:
    pip install edsl

Usage:
    python reproduce.py
"""
import json
from pathlib import Path

from edsl import Survey, AgentList, ScenarioList, Model, ModelList

HERE = Path(__file__).resolve().parent

# --- Load serialized objects ---
with open(HERE / "survey.json") as f:
    survey = Survey.from_dict(json.load(f))

with open(HERE / "agents.json") as f:
    agents = AgentList.from_dict(json.load(f))

with open(HERE / "scenarios.json") as f:
    scenarios_raw = json.load(f)

# Re-attach FileStore references to local screen PNGs
from edsl import FileStore, Scenario
scenarios = []
for s_data in scenarios_raw.get("scenarios", scenarios_raw.get("data", [])):
    rebuilt = {}
    for key, val in s_data.items():
        if key in ("edsl_version", "edsl_class_name"):
            continue
        if isinstance(val, dict) and "path" in val:
            rebuilt[key] = FileStore(str(HERE / val["path"]))
        else:
            rebuilt[key] = val
    scenarios.append(Scenario(rebuilt))
scenarios = ScenarioList(scenarios)

models = ModelList([Model(m) for m in ["claude-sonnet-4-6"]])

# Run per condition with matched sample sizes (as in original study)
condition_ns = {"A10_lottery": 50, "A10_mirror": 50, "A15_lottery": 50, "A15_mirror": 50, "G10_lottery": 50, "G10_mirror": 50, "G25_lottery": 50, "G25_mirror": 50, "G50_lottery": 50, "G50_mirror": 50, "G75_lottery": 50, "G75_mirror": 50, "G90_lottery": 50, "G90_mirror": 50, "L10_lottery": 50, "L10_mirror": 50, "L25_lottery": 50, "L25_mirror": 50, "L50_lottery": 50, "L50_mirror": 50, "L75_lottery": 50, "L75_mirror": 50, "L90_lottery": 50, "L90_mirror": 50}
all_results = []
for scenario in scenarios:
    cond = scenario.get("condition", None)
    cond_n = condition_ns.get(cond, len(agents))
    cond_agents = AgentList(list(agents)[:cond_n])
    print(f"Running condition '{cond}': {len(cond_agents)} agents")
    job = survey.by(cond_agents).by(models).by(ScenarioList([scenario]))
    results = job.run(cache=False, disable_remote_cache=True)
    all_results.append(results.to_pandas())

import pandas as pd
results_df = pd.concat(all_results, ignore_index=True)

print(f"Got {len(results_df)} responses")
results_df.to_csv("results_visual.csv", index=False)
print(f"Saved to results_visual.csv")
